version: '3.8'

services:
  postgres:
    container_name: student-market-postgres
    image: bitnami/postgresql:15
    env_file:
      - .env
    ports:
      - "5433:5432"  # Expose port 5432 from the container to host 5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 2s
      timeout: 10s
      retries: 5
    networks:
      - student-market-network

  minio:
    container_name: student-market-minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    command: server /data --console-address ":9001"
    networks:
      - student-market-network

  app:
    container_name: student-market-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"  # Expose app on port 8085
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - student-market-network

networks:
  student-market-network:
    driver: bridge
