name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd server
          mvn clean package -DskipTests
      - name: Update dependency graph
        if: always()
        run: |
          cd server  
          mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
      - name: Run Flyway Migrations
        run: |
          cd server
          mvn flyway:migrate -Dflyway.version=9.16.1 -Dflyway.user=postgres -Dflyway.password=9 -Dflyway.schemas=public
      - name: Run Tests
        run: |
          cd server
          mvn test
